version: "3.9"

services:
  db:
    image: postgres:15
    container_name: queijaria_db
    environment:
      POSTGRES_USER: pedro
      POSTGRES_PASSWORD: S1S1@12
      POSTGRES_DB: queijaria
    ports:
      - "5432:5432"
    volumes:
      - queijaria_pro_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pedro -d queijaria"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queijaria_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://pedro:S1S1@12@db:5432/queijaria
      DATA_DIR: /app/data
    volumes:
      - ./:/app:cached
      - ./data:/app/data
    command: ["python", "src/backend/etl/load.py"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queijaria_frontend
    depends_on:
      - db
      - app
    environment:
      DATABASE_URL: postgresql+psycopg2://pedro:S1S1@12@db:5432/queijaria
      DATA_DIR: /app/data
    volumes:
      - ./:/app:cached
      - ./data:/app/data
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "src/frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]

volumes:
  queijaria_pro_postgres_data:
